//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Global.proto
namespace com.gable.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Global")]
  public partial class Global : global::ProtoBuf.IExtensible
  {
    public Global() {}
    
    private string _string_value = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"string_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string string_value
    {
      get { return _string_value; }
      set { _string_value = value; }
    }
    private int _int_value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int int_value
    {
      get { return _int_value; }
      set { _int_value = value; }
    }
    private bool _bool_value = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bool_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bool_value
    {
      get { return _bool_value; }
      set { _bool_value = value; }
    }
    private float _float_value = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"float_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float float_value
    {
      get { return _float_value; }
      set { _float_value = value; }
    }
    private string _vector2_value = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vector2_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string vector2_value
    {
      get { return _vector2_value; }
      set { _vector2_value = value; }
    }
    private string _vector3_value = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vector3_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string vector3_value
    {
      get { return _vector3_value; }
      set { _vector3_value = value; }
    }
    private string _vector4_value = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"vector4_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string vector4_value
    {
      get { return _vector4_value; }
      set { _vector4_value = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _int_value_arr = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"int_value_arr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> int_value_arr
    {
      get { return _int_value_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _string_value_arr = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(9, Name=@"string_value_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> string_value_arr
    {
      get { return _string_value_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _bool_value_arr = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(10, Name=@"bool_value_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> bool_value_arr
    {
      get { return _bool_value_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _float_value_arr = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(11, Name=@"float_value_arr", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> float_value_arr
    {
      get { return _float_value_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _vector2_value_arr = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(12, Name=@"vector2_value_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> vector2_value_arr
    {
      get { return _vector2_value_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _vector3_value_arr = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(13, Name=@"vector3_value_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> vector3_value_arr
    {
      get { return _vector3_value_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _vector4_value_arr = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(14, Name=@"vector4_value_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> vector4_value_arr
    {
      get { return _vector4_value_arr; }
    }
  
    private float _baifen = default(float);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"baifen", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float baifen
    {
      get { return _baifen; }
      set { _baifen = value; }
    }
    private float _qianfen = default(float);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"qianfen", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float qianfen
    {
      get { return _qianfen; }
      set { _qianfen = value; }
    }
    private float _wanfen = default(float);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"wanfen", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float wanfen
    {
      get { return _wanfen; }
      set { _wanfen = value; }
    }
    private int _time_value = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"time_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time_value
    {
      get { return _time_value; }
      set { _time_value = value; }
    }
    private long _date_value = default(long);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"date_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long date_value
    {
      get { return _date_value; }
      set { _date_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GlobalTable")]
  public partial class GlobalTable : global::ProtoBuf.IExtensible
  {
    public GlobalTable() {}
    
    private com.gable.proto.Global _table = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"table", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.gable.proto.Global table
    {
      get { return _table; }
      set { _table = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}