//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: HeroQuality.proto
namespace com.gable.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"HeroQuality")]
    public enum HeroQuality
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Value_0", Value=0)]
      Value_0 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Value_2", Value=2)]
      Value_2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Value_3", Value=3)]
      Value_3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Value_4", Value=4)]
      Value_4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Value_5", Value=5)]
      Value_5 = 5
    }
  
}