//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Unit.proto
namespace com.gable.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Unit")]
  public partial class Unit : global::ProtoBuf.IExtensible
  {
    public Unit() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _string_value = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"string_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string string_value
    {
      get { return _string_value; }
      set { _string_value = value; }
    }
    private bool _bool_value = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bool_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bool_value
    {
      get { return _bool_value; }
      set { _bool_value = value; }
    }
    private float _float_test = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"float_test", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float float_test
    {
      get { return _float_test; }
      set { _float_test = value; }
    }
    private string _vector2_value = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vector2_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string vector2_value
    {
      get { return _vector2_value; }
      set { _vector2_value = value; }
    }
    private string _vector3_value = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vector3_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string vector3_value
    {
      get { return _vector3_value; }
      set { _vector3_value = value; }
    }
    private string _vector4_value = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"vector4_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string vector4_value
    {
      get { return _vector4_value; }
      set { _vector4_value = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _int_arr = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"int_arr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> int_arr
    {
      get { return _int_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _string_arr = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(9, Name=@"string_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> string_arr
    {
      get { return _string_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _bool_arr = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(10, Name=@"bool_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> bool_arr
    {
      get { return _bool_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _float_arr = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(11, Name=@"float_arr", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> float_arr
    {
      get { return _float_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _vector2_arr = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(12, Name=@"vector2_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> vector2_arr
    {
      get { return _vector2_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _vector3_arr = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(13, Name=@"vector3_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> vector3_arr
    {
      get { return _vector3_arr; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _vector4_arr = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(14, Name=@"vector4_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> vector4_arr
    {
      get { return _vector4_arr; }
    }
  
    private float _percentage_value = default(float);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"percentage_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float percentage_value
    {
      get { return _percentage_value; }
      set { _percentage_value = value; }
    }
    private float _permillage_value = default(float);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"permillage_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float permillage_value
    {
      get { return _permillage_value; }
      set { _permillage_value = value; }
    }
    private float _permian_value = default(float);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"permian_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float permian_value
    {
      get { return _permian_value; }
      set { _permian_value = value; }
    }
    private int _time_value = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"time_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time_value
    {
      get { return _time_value; }
      set { _time_value = value; }
    }
    private long _date_value = default(long);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"date_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long date_value
    {
      get { return _date_value; }
      set { _date_value = value; }
    }
    private int _enum_value = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"enum_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int enum_value
    {
      get { return _enum_value; }
      set { _enum_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitTable")]
  public partial class UnitTable : global::ProtoBuf.IExtensible
  {
    public UnitTable() {}
    
    private readonly global::System.Collections.Generic.List<com.gable.proto.Unit> _items = new global::System.Collections.Generic.List<com.gable.proto.Unit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.gable.proto.Unit> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}